#ifndef __ESP8266_ONENET_H__
#define __ESP8266_ONENET_H__

#include "stm32g4xx_hal.h"

#define ONENET_WIFI_SSID              "1505"
#define ONENET_WIFI_PASSWORD          "2359481815"
#define ONENET_PRODUCT_ID             "D283E5KDGV"
#define ONENET_DEVICE_NAME            "test"
#define ONENET_MQTT_TOKEN             "version=2018-10-31&res=products%2FD283E5KDGV%2Fdevices%2Ftest&et=4102416000&method=md5&sign=7ryU6xD%2FbtP989xt0BKouA%3D%3D"

/* New OneNET MQTT product domain. Despite "mqtts" in the host, port 1883 is plain MQTT. */
#define ONENET_MQTT_HOST              "mqtts.heclouds.com"
#define ONENET_MQTT_HOST_BACKUP       ONENET_PRODUCT_ID ".mqtts.acc.cmcconenet.cn"
#define ONENET_MQTT_HOST_BACKUP2      "studio-mqtt.heclouds.com"
#define ONENET_MQTT_PORT              1883U
#define ONENET_UPLOAD_INTERVAL_MS     10000U
#define ESP8266_ENABLE_LOOPBACK_TEST  0U

typedef enum
{
  ESP8266_ONENET_STATUS_OFFLINE = 0,
  ESP8266_ONENET_STATUS_WIFI_CONNECTED,
  ESP8266_ONENET_STATUS_MQTT_CONNECTED,
  ESP8266_ONENET_STATUS_CONFIG_MISSING
} ESP8266_OneNET_Status_t;

typedef enum
{
  ESP8266_ONENET_ERROR_NONE = 0,
  ESP8266_ONENET_ERROR_CONFIG,
  ESP8266_ONENET_ERROR_AT,
  ESP8266_ONENET_ERROR_MODE,
  ESP8266_ONENET_ERROR_JOIN_AP,
  ESP8266_ONENET_ERROR_USERCFG,
  ESP8266_ONENET_ERROR_LONG_PASSWORD,
  ESP8266_ONENET_ERROR_CONN_CFG,
  ESP8266_ONENET_ERROR_MQTT_CONNECT,
  ESP8266_ONENET_ERROR_PUBLISH,
  ESP8266_ONENET_ERROR_LOOPBACK_OK,
  ESP8266_ONENET_ERROR_GPIO_LOOPBACK_OK,
  ESP8266_ONENET_ERROR_GPIO_LOOPBACK_FAIL,
  ESP8266_ONENET_ERROR_RX_IDLE_LOW,
  ESP8266_ONENET_ERROR_JOIN_AP_TIMEOUT,
  ESP8266_ONENET_ERROR_JOIN_AP_PASSWORD,
  ESP8266_ONENET_ERROR_JOIN_AP_NOT_FOUND,
  ESP8266_ONENET_ERROR_JOIN_AP_FAILED,
  ESP8266_ONENET_ERROR_JOIN_AP_FAIL_RESPONSE,
  ESP8266_ONENET_ERROR_MQTT_CONNECT_DISCONNECTED,
  ESP8266_ONENET_ERROR_MQTT_CONNECT_FAIL_RESPONSE
} ESP8266_OneNET_Error_t;

void ESP8266_OneNET_Init(UART_HandleTypeDef *huart);
void ESP8266_OneNET_Task(void);
uint8_t ESP8266_OneNET_PostTempHumi(float temperature, float humidity, float lux, int heartrate, float spo2);
ESP8266_OneNET_Status_t ESP8266_OneNET_GetStatus(void);
ESP8266_OneNET_Error_t ESP8266_OneNET_GetLastError(void);
const char *ESP8266_OneNET_GetLastResponse(void);

#endif
